# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attack_events.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(707, 495)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = LineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.data = TableWidget(Form)
        self.data.setObjectName("data")
        self.data.setColumnCount(5)
        self.data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.data.setHorizontalHeaderItem(4, item)
        self.data.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.data)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Attack Events"))
        self.label_2.setText(_translate("Form", "fliter"))
        item = self.data.horizontalHeaderItem(0)
        item.setText(_translate("Form", "No"))
        item = self.data.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Time"))
        item = self.data.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Sourse"))
        item = self.data.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Destination"))
        item = self.data.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Length"))
from qfluentwidgets import LineEdit, TableWidget
